# Generated by Django 4.0.3 on 2022-03-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('artist', models.CharField(blank=True, default='', max_length=100)),
                ('album', models.CharField(blank=True, default='', max_length=100)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('release_date', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'music_library_database',
            },
        ),
    ]
